name: Publish to Docker Hub

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  publish-to-docker:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          BRANCH=$(git rev-parse --abbrev-ref HEAD)
          echo "BRANCH: ${BRANCH}"
          DOCKER_TAGS="${BRANCH},latest"
          echo "DOCKER_TAGS=${DOCKER_TAGS}" >> $GITHUB_ENV

      - name: Publish Docker Github Action
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: mvhsolutions/diegesis-server
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          dockerfile: Dockerfile
          tags: ${{ env.DOCKER_TAGS }}
